config/routes.rb
Blocitoff::Application.routes.draw do
  resources :lists

  get 'items/index'

  get 'items/show'

  get 'items/create'

  get 'items/new'

  get 'items/edit'



  devise_for :users
    resources :users, only: [:update, :show]

    resources :lists do
    resources :items, only: [:create]
  end

  authenticated :user do
    root to: "users#show", as: :authenticated_root, via: :get
  end

  unauthenticated do
    root 'welcome#index'
  end
end

app/models/coupon.rb
class Coupon < ActiveRecord::Base
  belongs_to :order

  #create order/coupons inside a controller
  params = { :order => { :name => '2-1 Orders', :coupons_attributes => { :coupon_name => '10% discount' } } }

  #create new order and coupons
  Order.create(params[:order])

  #update a coupon
  params = { :order => { :coupon_attributes => { :id => '2', :coupon_name => '15% discount' } } }
  order.update_attributes params[:order]

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :list
end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :user
  has_many :items, dependent: :destroy
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :items

  # Order has 1 to many assocation with coupons
  has_many :coupons

  # Add coupons as nested attribute to order
  # ":allow_destroy => :true" allows an edit form to remove a coupon
  # ":reject_if" rejects saving the form data if no attributes are entered in the coupon form
  accepts_nested_attributes_for :coupons, :allow_destroy => :true  ,
    :reject_if => proc { |attrs| attrs.all? { |key, value| value.blank? } }

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :lists, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
    before_action :configure_permitted_parameters, if: :devise_controller?
 
   protected
 
   def configure_permitted_parameters
     devise_parameter_sanitizer.for(:sign_up) << :name
   end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
  end

    def show
    end

   def new
    @list = List.find(params[:list_id])
    @item = Item.new(item_params)
    @item.list = @list

    if @item.save
     redirect_to list_path(@list), notice: "To-do saved."
    else
      flash[:error] = "Error saving To-do - please try again."
      render :new
    end
  end



  private

  def item_params
    params.require(:item).permit(:name)
  end

 
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:title, :description)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:order_name)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @lists = current_user.lists
  end

  def new
    @list = List.new
  end


  def create
    @list = current_user.lists.build(list_params)
    
    if @list.save
     redirect_to list_path(@list), notice: "List saved."
    else
      flash[:error] = "Error saving list - please try again."
      render :new
    end
  end

  def update
    if current_user.update_attributes(user_params)
      flash[:notice] = "User information updated"
      redirect_to edit_user_registration_path
    else
      flash[:error] = "Invalid user information"
      redirect_to edit_user_registration_path
    end
  end

  def show
    if params[:id]
      @user = User.find params[:id]
    else
      @user = current_user
    end
  end

  def edit
  end
  
  private

  def user_params
    params.require(:user).permit(:name)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_form.html.erb
<%= form_for [list, list.items.new] do |f| %>
    <div class="form-group">
    <%= f.text_field :name, class: 'form-control', placeholder: "Enter another To-do item" %>
    </div>
    <div class="form-group">
      <%= f.submit "Add To-do", class: 'btn btn-success' %>
    </div>
<% end %>

app/views/items/_item.html.erb
<ul class="list-item">
  <% list.items.each do |item| %>
    <li class="list-item bloc-item"><%= item.name %></li>
  <% end %>
 </ul>

app/views/items/create.html.erb
<h1>Items#create</h1>
<p>Find me in app/views/items/create.html.erb</p>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<% form_for([@order, @item]) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :item_name %><br />
    <%= f.text_field :item_name %>
  </p>
  <p>
    <%= f.submit "Update" %>
  </p>
<% end %>

<%= link_to 'Show', order_item_path(@order, @item) %> |
<%= link_to 'Back', order_items_path(@order) %>

app/views/items/index.html.erb
<h1>Items in <%= @order.order_name %></h1>

<table>
  <tr>
    <th>Item name</th>
  </tr>

<% for item in @items %>
  <tr>
    <td><%= item.item_name %></td>
    <td><%= link_to 'Show', order_item_path(@order, item) %></td>
    <td><%= link_to 'Edit', edit_order_item_path(@order, item) %></td>
    <td><%= link_to 'Destroy', order_item_path(@order, item), :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New item', new_order_item_path(@order) %>
<%= link_to 'Back to Order', @order %>

app/views/items/new.html.erb
<h1>New item</h1>

<% form_for([@order, @item]) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :item_name %><br />
    <%= f.text_field :item_name %>
  </p>
  <p>
    <%= f.submit "Create" %>
  </p>
<% end %>

<%= link_to 'Back', order_items_path(@order) %>

app/views/items/show.html.erb
<h1>Item in <%= @order.order_name %></h1>

<p>
  <b>Order name:</b>
  <%= @order.order_name %>
</p>

<!-- Display items of an order -->
<h2>Items</h2>
<% @order.items.each do |item| %>
  <p>
    <b>Item name:</b>
    <%= item.item_name %>
  </p>
<% end %>


<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %> |
<%= link_to 'Show Items', order_items_path(@order) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= link_to Blocitoff, root_path %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
  <body>
     <ul class="nav nav-tabs">
      <div class="pull-right user-info">
        <% if current_user %>
           Hello <%= link_to (current_user.name || current_user.email), edit_user_registration_path %>! <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
          <% else %>
            <%= link_to "Sign In", new_user_session_path %> or
              <%= link_to "Sign Up", new_user_registration_path %>
        <% end %>
      </div>
    </ul>
    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:error] %>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:error] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>
    
    </div>

  <%= yield %>

  </body>
</html>

app/views/lists/_form.html.erb
<%= form_for(@list) do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% @list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>Editing List</h1>

<%= render 'form' %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Lists</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lists.each do |list| %>
      <tr>
        <td><%= list.title %></td>
        <td><%= list.description %></td>
        <td><%= link_to 'Show', list %></td>
        <td><%= link_to 'Edit', edit_list_path(list) %></td>
        <td><%= link_to 'Destroy', list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New List', new_list_path %>

app/views/lists/new.html.erb
<h1>New List</h1>

<div class="row">
  <%= render partial: 'form', locals: { user: @user, list: @list } %>
</div>

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @list.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @list.description %>
</p>

<%= link_to 'Edit', edit_list_path(@list) %> |
<%= link_to 'Back', lists_path %>

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :order_name %><br>
    <%= f.text_field :order_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form' %>



<% @order.coupons.build if @order.coupons.empty? %>

<% form_for(@order) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :order_name %><br />
    <%= f.text_field :order_name %>
  </p>

  <h2>Coupons</h2>
  <% f.fields_for :coupons do |f2| %>
    <p>
      <%= f2.label :coupon_name, 'Coupon:' %>
      <%= f2.text_field :coupon_name %>
    </p>
    <% unless f2.object.nil? || f2.object.new_record? %>
      <p>
        <%= f2.label :_delete, 'Remove:' %>
        <%= f2.check_box :_delete %>
      </p>
    <% end %>
  <% end %>

  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Orders</h1>

<table>
  <thead>
    <tr>
      <th>Order name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.order_name %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Order name:</strong>
  <%= @order.order_name %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<h3>User</h3>
  <h4><p>Name: <%= @user.name if @user.name %></p>
  <p>Email: <%= @user.email if @user.email %></p></h4>

app/views/welcome/about.html.erb
<h1>Welcome to Blocitoff</h1>
<p>Self-Destructing To-Do Lists - An Alex Singleton Production</p>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <h1>Welcome To Blocitoff</h1>
  <p>Create your very own self-destructing to-do list!</p>
  <p>
      <%= link_to "Sign In", new_user_session_path, class: 'btn btn-primary' %> or
      <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary' %> today!
  </p>
</div>